FROM eclipse-temurin:8-jdk-jammy AS jdk8

FROM ghcr.io/astral-sh/uv:python3.12-trixie

ENV JAVA_HOME=/opt/java/openjdk
COPY --from=jdk8 $JAVA_HOME $JAVA_HOME
ENV PATH="${JAVA_HOME}/bin:${PATH}"

RUN adduser agentbeats
USER agentbeats
RUN mkdir -p /home/agentbeats/.cache/uv
WORKDIR /home/agentbeats/tutorial

COPY pyproject.toml uv.lock README.md ./
COPY src src

RUN \
    --mount=type=cache,target=/home/agentbeats/.cache/uv,uid=1000 \
    uv sync --locked

COPY tutorial scenarios

ENTRYPOINT ["uv", "run", "scenarios/mcu_agent.py"]
CMD ["--host", "0.0.0.0"]
EXPOSE 9019
